# Generated by Django 3.2.8 on 2021-11-19 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('poke_id', models.IntegerField(primary_key=True, serialize=False)),
                ('poke_name', models.CharField(max_length=30)),
                ('poke_pic', models.ImageField(upload_to='uploads/')),
                ('low_num', models.IntegerField()),
                ('high_num', models.IntegerField()),
                ('wild_pokemon', models.BooleanField(default=True)),
            ],
        ),
    ]
